[package]
name = 'UnityLib'
version = '0.1.0'
authors = ['Connor Ramsden <connor.ramsden@mymail.champlain.edu>']
edition = '2018'

[dependencies]
ffi-support = '0.3.5'
bindgen = "0.52.0"
cgmath = "0.17.0"

[lib]
name = 'unity_ffi'
crate-type = ['dylib']
